import type { Metadata } from "next";
import { Open_Sans, Montserrat} from "next/font/google";
import "./globals.css";
import "./colorsProj.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const montsserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${montsserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
