# Generated by Django 5.2.8 on 2025-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.URLField(verbose_name='URL da Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Imagem do Post',
                'verbose_name_plural': 'Imagens dos Posts',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
