# Generated by Django 5.2.8 on 2025-11-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('id_usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_como_usuario1', to='users.users', verbose_name='Usuário 1')),
                ('id_usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_como_usuario2', to='users.users', verbose_name='Usuário 2')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-data_atualizacao'],
                'unique_together': {('id_usuario1', 'id_usuario2')},
            },
        ),
    ]
